# Site settings
title: cc
author: carly culver
email: carlyeeculver@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Graphic and UI/UX Design works by Carly Culver
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.carlyculver.design" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
disqus_shortname: "demo_site"
keywords: ["your", "key", "words"]
pagination: 3

# Build settings
markdown: kramdown

# SASS Dir
sass:
    sass_dir: assets

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap