# Site settings
title: carly culver
author: carly culver
email: carlyeeculver@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carlyculver.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
disqus_shortname: "demo_site"
keywords: ["your", "key", "words"]
pagination: 3

# Build settings
markdown: kramdown

# SASS Dir
sass:
    sass_dir: assets

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap