# Site settings
title: Scoutahead
description: > # this means to ignore newlines until "baseurl:"
  Be better at your job by understanding your strengths and weaknesses. It can be difficult to be objective about yourself and your colleagues, but now there is a way to get the information you need to improve.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://scoutahead.com" # the base hostname & protocol for your site
twitter_username: ScoutaheadHQ
facebook_username: ScoutaheadHQ
keywords: ["professionals", "students", "companies", "career", "jobs", "survey", "self improvement"]
pagination: 3

# Build settings
markdown: kramdown

include: [_css, _assets]

exclude: [README.md, bower.json, Gemfile, Gemfile.lock ]

# SASS Dir
sass:
    sass_dir: _assets

collections:
  faqs:
    output: false
    permalink: /faqs/:path/
  welcomes:
    output: true
    permalink: /welcome/:path/

defaults:
  -
    scope:
      path: ""
      type: "welcomes" # a collection in your site, in plural form
    values:
      slug: "welcome"
      order: -1
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- octopress-autoprefixer
