# Site settings
title: Angular Jekyll Demo Site
author: Adrian Jon Miller
email: adrianjonmiller@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the demo site of my angular-jekyll framework
baseurl: "angular-jekyll/" # the subpath of your site, e.g. /blog/
url: "http://www.adrianjmiller.me/" # the base hostname & protocol for your site
twitter_username: adrianjmiller
github_username:  adrianjmiller
disqus_shortname: "demo_site"
keywords: ["jekyll", "angular", "framework"]
pagination: 10

# Build settings
markdown: kramdown

# SASS Dir
sass:
    sass_dir: assets


collections:
  products:
    output: true
    permalink: /products/:path/

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap